# Generated by Django 4.2 on 2023-04-14 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0003_connectionrequest_dismissed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='connectionrequest',
            name='status',
            field=models.CharField(choices=[(0, 'Pending'), (1, 'Accepted'), (2, 'Dismissed')], default=0, max_length=1),
        ),
    ]
