# Generated by Django 3.2.18 on 2023-04-14 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0005_alter_connectionrequest_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='connectionrequest',
            name='accepted',
        ),
        migrations.RemoveField(
            model_name='connectionrequest',
            name='dismissed',
        ),
    ]
