# Generated by Django 3.2.18 on 2023-04-14 22:21

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('connections', '0006_auto_20230414_2300'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ConnectionRequest',
            new_name='Connection',
        ),
    ]
