# Generated by Django 3.2.18 on 2023-04-14 23:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0008_conversation_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='connection',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='connections.connection'),
        ),
    ]
