# Generated by Django 4.2 on 2023-04-13 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_topic_is_private'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
